# Dependabot configuration file.
# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "octocat"
    reviewers:
      - "octocat"
    commit-message:
      prefix: "pip"
      include: "scope"
    versioning-strategy: auto

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "octocat"
    commit-message:
      prefix: "github-actions"
      include: "scope"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "octocat"
    commit-message:
      prefix: "docker"
      include: "scope"
      
  # Maintain dependencies for npm (if there are JavaScript/TypeScript libraries in your project)
  - package-ecosystem: "npm"
    directory: "/static"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
    assignees:
      - "octocat"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      # Ignore updates to packages that start with 'dev-'
      - dependency-name: "dev-*"
      
  # Allow security updates for all ecosystems
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "security"
      include: "scope"
    target-branch: "main"
    security-updates-only: true