version: '3.8'

services:
  api:
    build: .
    container_name: bloxapi
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=change-this-to-a-secure-value
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bloxapi
    depends_on:
      - db
    networks:
      - bloxapi-network

  db:
    image: postgres:14
    container_name: bloxapi-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bloxapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bloxapi-network

networks:
  bloxapi-network:
    driver: bridge

volumes:
  postgres_data: