services:
  - type: web
    name: bloxapi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    healthCheckPath: /health
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bloxapi-db
          property: connectionString

databases:
  - name: bloxapi-db
    databaseName: bloxapi
    user: bloxapi_user
    plan: free