name: Feature Request
description: Suggest an idea for BloxAPI
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - Bogdan11212
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for BloxAPI!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like BloxAPI to [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have tried using [...]
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve usability
        - High - Critical functionality missing
    validations:
      required: true
  - type: dropdown
    id: api_category
    attributes:
      label: API Category
      description: Which part of the API does this feature relate to?
      options:
        - Users API
        - Games API
        - Groups API
        - Assets API
        - Catalog API
        - Economy API
        - Badges API
        - Events API
        - Moderation API
        - Statistics API
        - Servers API
        - Social API
        - Monetization API
        - Other/General
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true