name: Generate Visual Widgets

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/generate-widgets.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/generate-widgets.yml'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-widgets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairosvg pillow matplotlib numpy svgwrite pyyaml requests
          
      - name: Generate Logo and Badges
        run: |
          python scripts/widget_builder.py --generate-all
          
      - name: Update README with Stats
        run: |
          python scripts/update_readme_stats.py
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "🎨 Update visual widgets and project statistics"
          title: "🎨 Update visual widgets and project statistics"
          body: |
            ## Automated Widget Update
            
            This PR was automatically generated to update the visual elements of the project:
            
            - Updated project statistics in README
            - Generated new badges and widgets
            - Updated SVG assets in docs/images
            
            The changes maintain the visual theme and branding of BloxAPI while ensuring all statistics are current.
          branch: automated-widget-update
          base: main
          labels: |
            automated
            documentation
            visual-improvements