name: Generate Visual Assets

on:
  push:
    branches: [ main, master, dev ]
    paths:
      - 'widget_builder.py'
      - 'badges/*.json'
      - '.github/workflows/generate-visuals.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install svgwrite pillow numpy matplotlib
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin
          
      - name: Generate visual assets
        run: |
          python widget_builder.py --all
          
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/images/* docs/badges/* static/images/* || true
          git commit -m "Auto-generate visual assets [skip ci]" || true
          git push
          
      - name: Ensure Workflow Persistence
        run: |
          echo "Workflow completed successfully."