name: Update README Badges

on:
  push:
    branches: [ main, master, dev ]
    paths:
      - 'badges/*.json'
      - '.github/workflows/update-badges.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update version badge
        run: |
          # Update version from package information or git tags
          python scripts/update_readme_stats.py --badge version
          
      - name: Update feature count badge
        run: |
          # Count API endpoints and update badge
          python scripts/update_readme_stats.py --badge feature-count
          
      - name: Update security badge
        run: |
          # Check security status and update badge
          python scripts/update_readme_stats.py --badge security
          
      - name: Update Python versions badge
        run: |
          # Update supported Python versions badge
          python scripts/update_readme_stats.py --badge python-versions
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add badges/*.json
          git commit -m "Update badges [skip ci]" || true
          git push